export const SEQUELIZE = "SEQUELIZE";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const HOSPITAL_REPOSITORY = 'HOSPITAL_REPOSITORY';
export const VACCINE_REPOSITORY = 'VACCINE_REPOSITORY';
export const PATIENT_REPOSITORY = 'PATIENT_REPOSITORY';
export const RECORD_REPOSITORY = 'RECORD_REPOSITORY';
export const VACINNELIST_REPOSITORY = 'VACCINELIST_REPOSITORY';
export const NEWS_REPOSITORY = 'NEWS_REPOSITORY';